server:
  port: 9001

spring:
  application:
    name: muse_send #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos server地址

management:
  endpoints:
    web:
      exposure:
        include: '*'