spring:
  application:
    name: muse_manager #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos server地址
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.229.44.186:1521/muse?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 824780260
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.qq.com
    port: 465     #qq邮箱465、587
    from: 1794970183@qq.com
    default-encoding: UTF-8  #qq邮箱
    protocol: smtp
    username: 1794970183@qq.com
    password: somtyxlnzrizbhhf
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
        display:
          sendmail: Javen
          sendname: Spring Boot
server:
  port: 9002

management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl