package mapper;

import model.Customer;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_email_setting
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_email_setting
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_email_setting
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_email_setting
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    Customer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_email_setting
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_email_setting
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    int updateByPrimaryKey(Customer record);
}