package model;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.id
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.uid
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.name
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.address
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.port
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private String port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.account
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.username
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.password
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.isSSL
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private Byte isssl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.isTLS
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private Byte istls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.createTime
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.updateTime
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.valid
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private Byte valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_email_setting.remark
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.id
     *
     * @return the value of m_email_setting.id
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.id
     *
     * @param id the value for m_email_setting.id
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.uid
     *
     * @return the value of m_email_setting.uid
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.uid
     *
     * @param uid the value for m_email_setting.uid
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.name
     *
     * @return the value of m_email_setting.name
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.name
     *
     * @param name the value for m_email_setting.name
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.address
     *
     * @return the value of m_email_setting.address
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.address
     *
     * @param address the value for m_email_setting.address
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.port
     *
     * @return the value of m_email_setting.port
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.port
     *
     * @param port the value for m_email_setting.port
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setPort(String port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.account
     *
     * @return the value of m_email_setting.account
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.account
     *
     * @param account the value for m_email_setting.account
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.username
     *
     * @return the value of m_email_setting.username
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.username
     *
     * @param username the value for m_email_setting.username
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.password
     *
     * @return the value of m_email_setting.password
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.password
     *
     * @param password the value for m_email_setting.password
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.isSSL
     *
     * @return the value of m_email_setting.isSSL
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public Byte getIsssl() {
        return isssl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.isSSL
     *
     * @param isssl the value for m_email_setting.isSSL
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setIsssl(Byte isssl) {
        this.isssl = isssl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.isTLS
     *
     * @return the value of m_email_setting.isTLS
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public Byte getIstls() {
        return istls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.isTLS
     *
     * @param istls the value for m_email_setting.isTLS
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setIstls(Byte istls) {
        this.istls = istls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.createTime
     *
     * @return the value of m_email_setting.createTime
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.createTime
     *
     * @param createtime the value for m_email_setting.createTime
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.updateTime
     *
     * @return the value of m_email_setting.updateTime
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.updateTime
     *
     * @param updatetime the value for m_email_setting.updateTime
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.valid
     *
     * @return the value of m_email_setting.valid
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.valid
     *
     * @param valid the value for m_email_setting.valid
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_email_setting.remark
     *
     * @return the value of m_email_setting.remark
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_email_setting.remark
     *
     * @param remark the value for m_email_setting.remark
     *
     * @mbg.generated Fri Oct 23 17:36:42 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}