spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/muse?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  mail:
    host: smtp.qq.com
    port: 465     #qq邮箱465、587
    from: 1794970183@qq.com
    default-encoding: UTF-8  #qq邮箱
    protocol: smtp
    username: 1794970183@qq.com
    password: somtyxlnzrizbhhf
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
        display:
          sendmail: Javen
          sendname: Spring Boot
server:
  port: 8083
